feat/add pagination
clucasalcantara/rethinkly pull request #16
Opened 2021-07-20 16:56 UTC by victorhugorch

2021-07-21 17:50 UTC, clucasalcantara requested changes
AWESOME! 👯 

Just left a few minors to fix :D

2021-07-21 17:50 UTC, clucasalcantara commented on src/transactions/pagination-data.js
> +    .orderBy('teste')
👀  We really need this orderBy here?

2021-07-21 17:50 UTC, clucasalcantara commented on src/transactions/database.js
> +    port: process.env.ENV === 'mock' ? '28015' : '55001',
I really think that this port should be fixed as 28015 and the fix should be done in the docker container mapping correctly the port exposure

2021-07-21 17:50 UTC, clucasalcantara commented on package.json
> +    "test:local": "ENV=local ava",
When fixing your docker to run at 28015 you don't gonna need this script as well :D

2021-07-29 15:48 UTC, victorhugorch commented
I added the suggested changes. Thanks for the review! <3

2021-07-30 19:22 UTC, clucasalcantara approved these changes

2021-07-30 19:23 UTC, merged